name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to DreamHost
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      
      - name: Pull and deploy
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H iad1-shared-b8-11.dreamhost.com >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_ed25519 dh_uj5z8b@iad1-shared-b8-11.dreamhost.com /home/dh_uj5z8b/hudsonvalleyticks.com/deploy.sh
